version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@dmin123
    ports:
      - 1433:1433

  printlayer:
    image: ${DOCKER_REGISTRY-}printlayer
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
